@backend_HostAddress = http://localhost:5083

//====================================================================== COMPANY ====================================================================

GET {{backend_HostAddress}}/api/companies/getAll/00000000-0000-0000-0000-000000000001
Content-Type: application/json

###Get by id
GET {{backend_HostAddress}}/api/companies/getById/4/00000000-0000-0000-0000-000000000001
Content-Type: application/json

### create a new company
POST {{backend_HostAddress}}/api/companies/create/00000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "CompanyName": "createATAction fix test",
  "WebsiteUrl": "Test.com",
  "Industry": "Logistic"
}

###Update a company
PUT {{backend_HostAddress}}/api/companies/update/6/00000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "CompanyName": "UserId tested",
  "WebsiteUrl": "Ichangetheurl.com",
  "Industry": ""
}

# Practive method, removed
# ###DElete by id
# DELETE {{backend_HostAddress}}/api/companies/3/00000000-0000-0000-0000-000000000001
# Content-Type: application/json

//====================================================================== JOB APPLICATION ====================================================================
###Get all
GET {{backend_HostAddress}}/api/jobApplications/getAll/00000000-0000-0000-0000-000000000002
Content-Type: application/json

###Get by id
GET {{backend_HostAddress}}/api/jobApplications/getById/5/00000000-0000-0000-0000-000000000002
Content-Type: application/json

###Create new JA
POST {{backend_HostAddress}}/api/jobApplications/create/00000000-0000-0000-0000-000000000002
Content-Type: application/json

{
  "companyId": 2,
  "jobTitle": "Status History auto create test",
  "jobPostingUrl": "https://careers.google.com/jobs/123",
  "location": "Remote",
  "dateApplied": "2026-08-27",
  "notes": "Applied through referral"
}

###Update by id
PUT {{backend_HostAddress}}/api/JobApplications/update/5/00000000-0000-0000-0000-000000000002
Content-Type: application/json

{
  "JobTitle": "Backend Dev",
  "notes": "Note field got updated"
}

###Update JA status
POST {{backend_HostAddress}}/api/JobApplications/updateStatus/5/00000000-0000-0000-0000-000000000002
Content-Type: application/json

{
  "Status": "Interviewing",
  "Note": "Test note"
}

###Get all status history
GET {{backend_HostAddress}}/api/JobApplications/getAllStatusHistoryById/13/00000000-0000-0000-0000-000000000002
Content-Type: application/json

###Job posting details upsert
PUT {{backend_HostAddress}}/api/JobApplications/jobPostingDetailsUpsert/6/00000000-0000-0000-0000-000000000002
Content-Type: application/json

{
  "RawText": "Lorem ispum",>
  "DetailsJson": "{\"aboutCompany\": \"A fast-growing startup\", \"whyJoinUs\": \"Great benefits and remote-first culture\"}"
}

###Get job posting detail by job application id
GET {{backend_HostAddress}}/api/JobApplications/jobPostingDetailsGetById/7/00000000-0000-0000-0000-000000000002
Content-Type: application/json

//===================================================== AUTHENTICATION =============================================
###Register
POST {{backend_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test01@gmail.com",
  "password": "Test1234!"
}

###Login
POST {{backend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test01@gmail.com",
  "password": "Test1234!"
}