@backend_HostAddress = http://localhost:5083

GET {{backend_HostAddress}}/api/companies
Content-Type: application/json

### create a new company
POST {{backend_HostAddress}}/api/companies
Content-Type: application/json

{
  "UserId": "00000000-0000-0000-0000-000000000001",
  "CompanyName": "Amazone",
  "WebsiteUrl": "",
  "Industry": "Logistic"
}

###Update a company
PUT {{backend_HostAddress}}/api/companies/3/00000000-0000-0000-0000-000000000001
Content-Type: application/json

{
  "CompanyName": "Google         ",
  "WebsiteUrl": "Ichangetheurl.com",
  "Industry": ""
}

# Practive method, removed
# ###DElete by id
# DELETE {{backend_HostAddress}}/api/companies/3/00000000-0000-0000-0000-000000000001
# Content-Type: application/json